### ISSUE TITLE
Listview scrolling and selecting Textfield afterwards is freezing my app

### ISSUE THREAD

**Issue by michael-ottink** [imtoori/CountryCodePicker#93] opened 2020-06-19 19:27 UTC
I am using flutter 1.17.3 and

      country_code_picker: ^1.4.0

@imtoori I am on a tight deadline for a project, so a quick response would be appreciated.

When I run this code

```
    import 'package:country_code_picker/country_code_picker.dart';
    import 'package:flutter/material.dart';
    
    void main() {
      runApp(App());
    }
    
    class App extends StatelessWidget {
      App();
    
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          debugShowCheckedModeBanner: false,
          home: TestWidget(),
        );
      }
    }
    
    class TestWidget extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return _buildCountryPicker(context);
      }
    
        Widget _buildCountryPicker(BuildContext context) {
    
        return Container(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height,
          child: Center(
            child: CountryCodePicker(
              initialSelection: 'NL',
            ),
          ),
        );
      }
    }
```

And I open the dialog to select a country. I scroll in the list and then select the TextField my keyboard opens and when I try to type something my entire app freezes. I can't even hot reload. I forked the repo and tried to fix it, except for that I don't have a singly clue what it could be. 

I am running this on my Huawei P30, but I also experience this on other android devices. I don't know if this is a flutter bug or a country code picker bug.

I think it is probably in this widget somewhere.

```
class SelectionDialog extends StatefulWidget {
      final List<CountryCode> elements;
      final bool showCountryOnly;
      final InputDecoration searchDecoration;
      final TextStyle searchStyle;
      final TextStyle textStyle;
      final WidgetBuilder emptySearchBuilder;
      final bool showFlag;
      final double flagWidth;
      final Size size;
      final bool hideSearch;
    
      /// elements passed as favorite
      final List<CountryCode> favoriteElements;
    
      SelectionDialog(
        this.elements,
        this.favoriteElements, {
        Key key,
        this.showCountryOnly,
        this.emptySearchBuilder,
        InputDecoration searchDecoration = const InputDecoration(),
        this.searchStyle,
        this.textStyle,
        this.showFlag,
        this.flagWidth = 32,
        this.size,
        this.hideSearch = false,
      })  : assert(searchDecoration != null, 'searchDecoration must not be null!'),
            this.searchDecoration =
                searchDecoration.copyWith(prefixIcon: Icon(Icons.search)),
            super(key: key);
    
      @override
      State<StatefulWidget> createState() => _SelectionDialogState();
    }
    
    class _SelectionDialogState extends State<SelectionDialog> {
      /// this is useful for filtering purpose
      List<CountryCode> filteredElements;
    
      @override
      Widget build(BuildContext context) => SimpleDialog(
            titlePadding: const EdgeInsets.all(0),
            title: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.end,
              children: <Widget>[
                IconButton(
                  padding: const EdgeInsets.all(0),
                  iconSize: 20,
                  icon: Icon(
                    Icons.close,
                  ),
                  onPressed: () => Navigator.pop(context),
                ),
                if (!widget.hideSearch)
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 24),
                    child: TextField(
                      style: widget.searchStyle,
                      decoration: widget.searchDecoration,
                      onChanged: _filterElements,
                    ),
                  ),
              ],
            ),
            children: [
              Container(
                width: widget.size?.width ?? MediaQuery.of(context).size.width,
                height:
                    widget.size?.height ?? MediaQuery.of(context).size.height * 0.7,
                child: ListView(
                  children: [
                    widget.favoriteElements.isEmpty
                        ? const DecoratedBox(decoration: BoxDecoration())
                        : Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              ...widget.favoriteElements.map(
                                (f) => SimpleDialogOption(
                                  child: _buildOption(f),
                                  onPressed: () {
                                    _selectItem(f);
                                  },
                                ),
                              ),
                              const Divider(),
                            ],
                          ),
                    if (filteredElements.isEmpty)
                      _buildEmptySearchWidget(context)
                    else
                      ...filteredElements.map(
                        (e) => SimpleDialogOption(
                          key: Key(e.toLongString()),
                          child: _buildOption(e),
                          onPressed: () {
                            _selectItem(e);
                          },
                        ),
                      ),
                  ],
                ),
              ),
            ],
          );
    
      Widget _buildOption(CountryCode e) {
        return Container(
          width: 400,
          child: Flex(
            direction: Axis.horizontal,
            children: <Widget>[
              if (widget.showFlag)
                Flexible(
                  child: Padding(
                    padding: const EdgeInsets.only(right: 16.0),
                    child: Image.asset(
                      e.flagUri,
                      package: 'country_code_picker',
                      width: widget.flagWidth,
                    ),
                  ),
                ),
              Expanded(
                flex: 4,
                child: Text(
                  widget.showCountryOnly
                      ? e.toCountryStringOnly()
                      : e.toLongString(),
                  overflow: TextOverflow.fade,
                  style: widget.textStyle,
                ),
              ),
            ],
          ),
        );
      }
    
      Widget _buildEmptySearchWidget(BuildContext context) {
        if (widget.emptySearchBuilder != null) {
          return widget.emptySearchBuilder(context);
        }
    
        return Center(
          child: Text('No country found'),
        );
      }
    
      @override
      void initState() {
        filteredElements = widget.elements;
        super.initState();
      }
    
      void _filterElements(String s) {
        s = s.toUpperCase();
        setState(() {
          filteredElements = widget.elements
              .where((e) =>
                  e.code.contains(s) ||
                  e.dialCode.contains(s) ||
                  e.name.toUpperCase().contains(s))
              .toList();
        });
      }
    
      void _selectItem(CountryCode e) {
        Navigator.pop(context, e);
      }
    }
```

**Comment by michael-ottink** [comment] 2020-06-19 19:42
@imtoori  I think it has something to do with this

    key: Key(e.toLongString()),

Which probably creates a dulicate key.

**Comment by michael-ottink** [comment] 2020-06-19 20:19
I forked the repo and tried

```
 ...filteredElements.toSet().toList().map(
    (e) => SimpleDialogOption(
      key: Key(e.toLongString()),
      child: _buildOption(e),
      onPressed: () {
        _selectItem(e);
      },
    ),
  ),
```

And this did not work. So it is probably something else

**Comment by michael-ottink** [comment] 2020-06-19 21:00
I also get the message `SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length` could that have anything to do with it?

**Comment by imtoori** [comment] 2020-06-20 10:37
hey! Sorry but I'm really busy at the moment and it may take some time.
But I'm trying to understand the problem right now

**Comment by imtoori** [comment] 2020-06-20 10:55
@michael-ottink you should put a Scaffold in your page.
Try that and it will work

```dart
import 'package:country_code_picker/country_code_picker.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  App();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: TestWidget(),
    );
  }
}

class TestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(body: _buildCountryPicker(context));
  }

  Widget _buildCountryPicker(BuildContext context) {
    return Container(
      width: MediaQuery.of(context).size.width,
      height: MediaQuery.of(context).size.height,
      child: Center(
        child: CountryCodePicker(
          initialSelection: 'NL',
        ),
      ),
    );
  }
}

```

**Comment by michael-ottink** [comment] 2020-06-20 12:23
@imtoori I don't think so, I didn't put one in this example. But I had one in my app. Just to be sure I'll check it right now.

**Comment by michael-ottink** [comment] 2020-06-20 12:24
I tried the code you gave me buy it produced the same problem. I am running it on a physical device. I'll try and see if I can video clip it.

**Comment by michael-ottink** [comment] 2020-06-20 12:36
@imtoori I have a video of it happening right here https://www.youtube.com/watch?v=669KitFG9ek&feature=youtu.be this is with the scaffold

**Comment by michael-ottink** [comment] 2020-06-21 15:39
@imtoori Removing the key from the simple dialog option resolves the issue

```
                  ...filteredElements.map(
                    (e) => SimpleDialogOption(
                      // key: Key(e.toLongString()),
                      child: _buildOption(e),
                      onPressed: () {
                        _selectItem(e);
                      },
                    ),
```

Now it works. Not sure why the key was needed anyway? Because everything seems to still work.

**Comment by tneagu** [comment] 2020-07-06 06:11
Same problem here. The bug is very reproductible on every device, iOS and Android. 

Seems @michael-ottink fix solves the problem.

**Comment by ltvu93** [comment] 2020-07-13 09:01
@michael-ottink Please create the PR to fix this issue, so the author can review and merge it.

**Comment by Abdullah-Zakhoi** [comment] 2020-08-04 12:14
@michael-ottink  @imtoori I tried it without deleting key it's work well 

```
 ...filteredElements.map(
                    (e) => SimpleDialogOption(
                      key: Key(e.toLongString()),
                      child: _buildOption(e),
                      onPressed: () {
                        _selectItem(e);
                      },
                    ),
                  ),
```

the video of trying ...

<img width="250" height="500" alt="gif" src="https://user-images.githubusercontent.com/66040295/89292362-eed17700-d664-11ea-9cd6-b68b576d8f11.gif">

**Comment by imtoori** [comment] 2020-09-19 11:27
I'm sorry guys, but I've been too busy to deal with this
You should open a pr when you think there is something you can fix
The problem is that I've never had such a bug
I'll remove the key from the SimpleDialogOption if that works for you

**Comment by imtoori** [comment] 2021-03-13 11:49
Closing this
Feel free to reopen it if you're still having issues

**Closed by imtoori** 2021-03-13 11:49 UTC
